esphome:
  name: fetap-0111
  friendly_name: FeTAp 0111

esp32:
  board: az-delivery-devkit-v4
  framework:
    type:  esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  on_connect:
    - delay: 5s  # Gives time for improv results to be transmitted
    - ble.disable:
  on_disconnect:
    - ble.enable:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fetap-0111 Fallback Hotspot"
    password: ""

captive_portal:

improv_serial:

esp32_improv:
  authorizer: none

matrix_keypad:
  id: keypad
  rows:
    - pin: 4
    - pin: 16
    - pin: 17
    - pin: 5
  columns:
    - pin: 34
    - pin: 35
    - pin: 32
  keys: "123456789S0R"
  has_diodes: false

button:
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO33
    i2s_bclk_pin: GPIO19    
  - id: i2s_out
    i2s_lrclk_pin: GPIO21
    i2s_bclk_pin: GPIO18   


microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO23
    adc_type: external
    pdm: false    


speaker:
  - platform: i2s_audio
    id: echo_speaker
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO22
    dac_type: external
    mode: mono

voice_assistant:
  id: va
  microphone: echo_microphone
  speaker: echo_speaker
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 1.0
  vad_threshold: 3

  on_listening:  # An automation to perform when the voice assistant microphone starts listening.
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Slow Pulse"

  on_stt_vad_end: # An automation to perform when voice activity detection ends speech-to-text processing.
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Fast Pulse"

  on_tts_start:   #  An automation to perform when the voice assistant has started text-to-speech. The text to be spoken is available to automations as the variable x.
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness: 100%
        effect: none

  on_end:
    - delay: 100ms
    - wait_until:
        not:
          speaker.is_playing:
    - if:
        condition:
          - binary_sensor.is_on: cradle_button
          - switch.is_off: use_wake_word
        then:
          - delay: 500ms
          - switch.turn_on: use_wake_word
    - script.execute: reset_led

  on_client_connected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.start_continuous:
          - script.execute: reset_led
  on_client_disconnected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.stop:
          - light.turn_off: led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
    name: Cradle
    disabled_by_default: true
    id: cradle_button
    on_multi_click:
      - timing:
          - ON for at least 100ms
        then:
          - light.turn_off: ring_indicator
          - if:
              condition:
                switch.is_off: use_wake_word
              then:
                - if:
                    condition: voice_assistant.is_running
                    then:
                      - voice_assistant.stop:
                      - script.execute: reset_led
                    else:
                      - delay: 500ms
                      - voice_assistant.start:
      - timing:
          - OFF for at least 100ms
        then:
          if:
            condition:
              switch.is_on: use_wake_word
            then:
              - switch.turn_off: use_wake_word
            else:
              - voice_assistant.stop:
              - script.execute: reset_led
  - platform: matrix_keypad
    id: key1
    key: 1
    on_press:
      - switch.turn_on: keypad_1
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_1

  - platform: matrix_keypad
    id: key2
    key: 2
    on_press:
      - switch.turn_on: keypad_2
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_2

  - platform: matrix_keypad
    id: key3
    key: 3
    on_press:
      - switch.turn_on: keypad_3
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_3    

  - platform: matrix_keypad
    id: key4
    key: 4
    on_press:
      - switch.turn_on: keypad_4
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_4

  - platform: matrix_keypad
    id: key5
    key: 5
    on_press:
      - switch.turn_on: keypad_5
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_5

  - platform: matrix_keypad
    id: key6
    key: 6
    on_press:
      - switch.turn_on: keypad_6
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_6

  - platform: matrix_keypad
    id: key7
    key: 7
    on_press:
      - switch.turn_on: keypad_7
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_7

  - platform: matrix_keypad
    id: key8
    key: 8
    on_press:
      - switch.turn_on: keypad_8
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_8

  - platform: matrix_keypad
    id: key9
    key: 9
    on_press:
      - switch.turn_on: keypad_9
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_9    

  - platform: matrix_keypad
    id: key0
    key: 0
    on_press:
      - switch.turn_on: keypad_0
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_0

  - platform: matrix_keypad
    id: keyS
    key: S
    on_press:
      - switch.turn_on: keypad_S
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_S    

  - platform: matrix_keypad
    id: keyR
    key: R
    on_press:
      - switch.turn_on: keypad_R
      - script.execute: keypad_led
    on_release:
      switch.turn_off: keypad_R


output:
  - platform: ledc
    id: bell
    pin: GPIO12
    inverted: False

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: None
    disabled_by_default: true
    entity_category: config
    pin: GPIO27
    default_transition_length: 0s
    chipset: SK6812
    num_leds: 1
    rgb_order: rgb
    rmt_channel: 0
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%
  - platform: monochromatic
    id: ring_indicator
    name: "Bell"
    output: bell
    icon: mdi:bell-ring
    effects:
      - strobe:
          name: "Ring Ring (asym)"
          colors:
            - state: true
              brightness: 100%
              duration: 300ms
            - state: false
              duration: 600ms          
            - state: true
              brightness: 100%
              duration: 600ms
            - state: false
              duration: 2s
    on_turn_on:
     - light.turn_on:
         id: ring_indicator
         effect: "Ring Ring (asym)"        


script:
  - id: reset_led
    then:
      - if:
          condition:
            - switch.is_on: use_listen_light
          then:
            if:
              condition:
                switch.is_on: use_wake_word
              then:
                - light.turn_on:
                    id: led
                    red: 100%
                    green: 0%
                    blue: 0%
                    brightness: 30%
                    effect: "Slow Pulse"
              else:    
                - light.turn_on:
                    id: led
                    red: 0%
                    green: 100%
                    blue: 0%
                    brightness: 30%
                    effect: none
          else:
            - light.turn_off: led
  - id: keypad_led
    then:
      - light.turn_on:
          id: led
          red: 95%
          green: 88%
          blue: 0%
          brightness: 30%
      - delay: 200ms    
      - script.execute: reset_led


switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    on_turn_on:
      - lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running
          then:
            - voice_assistant.start_continuous
            - light.turn_on: 
                id: led
                red: 100%
                green: 0%
                blue: 0%
                effect: "Slow Pulse"
    on_turn_off:
      - voice_assistant.stop
      - lambda: id(va).set_use_wake_word(false);
      - script.execute: reset_led
  - platform: template
    name: Use Listen Light
    id: use_listen_light
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - script.execute: reset_led
    on_turn_off:
      - script.execute: reset_led

  - platform: template
    name: Key 1
    id: keypad_1
    icon: mdi:numeric-1-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: Key 2
    id: keypad_2
    icon: mdi:numeric-2-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: Key 3
    id: keypad_3
    icon: mdi:numeric-3-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: Key 4
    id: keypad_4
    icon: mdi:numeric-4-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: Key 5
    id: keypad_5
    icon: mdi:numeric-5-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF  
  - platform: template
    name: Key 6
    id: keypad_6
    icon: mdi:numeric-6-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF    
  - platform: template
    name: Key 7
    id: keypad_7
    icon: mdi:numeric-7-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: Key 8
    id: keypad_8
    icon: mdi:numeric-8-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: Key 9
    id: keypad_9
    icon: mdi:numeric-9-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: Key 0
    id: keypad_0
    icon: mdi:numeric-0-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: Key S
    id: keypad_S
    icon: mdi:star-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: Key Hashtag
    id: keypad_R
    icon: mdi:pound-box-outline
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    

    

external_components:
  - source: github://pr#5230
    components:
      - esp_adf
    refresh: 0s

esp_adf:    
